name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
          cache: true
      - name: Install dependencies
        run: go mod download
      - name: Install TinyGo
        run: sudo bash ./scripts/install-tinygo.sh
      - name: Install WABT
        run: sudo bash ./scripts/install-wabt.sh
      - name: Install AssemblyScript
        run: sudo bash ./scripts/install-asc.sh
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
